---
apiVersion: v1
kind: Service
metadata:
  name: k8s-3
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 10250
      targetPort: 10250
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-3
  namespace: kube-system
subsets:
  - addresses:
      - ip: 172.18.8.103
    ports:
      - port: 10250
